"""Durably enqueue public API commands with idempotent acceptance."""

from __future__ import annotations

import uuid
from typing import cast

from sqlalchemy import select, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from pulseexchange.models import CommandStatus, CommandType, MarketCommand, PersistedSide

# Separate from the processor lock: this serializes only the short journal
# acceptance transaction so PostgreSQL identity order also becomes commit /
# visibility order.
INGEST_ADVISORY_LOCK_ID = 6_029_117_904_286_302


class IdempotencyConflictError(Exception):
    """The key was previously used for a semantically different request."""


def _semantic_payload(command: MarketCommand) -> dict[str, object]:
    payload = dict(command.payload)
    if command.command_type == CommandType.SUBMIT_ORDER:
        # The identifier is generated by the server and belongs to the receipt,
        # not to the caller's semantic request.
        payload.pop("order_id", None)
    return payload


def _same_semantics(existing: MarketCommand, candidate: MarketCommand) -> bool:
    return (
        existing.command_type == candidate.command_type
        and existing.symbol == candidate.symbol
        and _semantic_payload(existing) == _semantic_payload(candidate)
    )


def _return_or_conflict(existing: MarketCommand, candidate: MarketCommand) -> MarketCommand:
    if not _same_semantics(existing, candidate):
        raise IdempotencyConflictError("Idempotency-Key was already used for a different request")
    return existing


async def _existing_by_key(session: AsyncSession, idempotency_key: str) -> MarketCommand | None:
    return cast(
        MarketCommand | None,
        await session.scalar(
            select(MarketCommand).where(MarketCommand.idempotency_key == idempotency_key)
        ),
    )


async def _acquire_ingest_lock(session: AsyncSession) -> None:
    bind = session.get_bind()
    if bind.dialect.name == "postgresql":
        await session.execute(
            text("SELECT pg_advisory_xact_lock(:lock_id)"),
            {"lock_id": INGEST_ADVISORY_LOCK_ID},
        )


async def _persist_idempotently(session: AsyncSession, command: MarketCommand) -> MarketCommand:
    """Serialize acceptance, then commit or return the prior semantic request.

    PostgreSQL identities are allocated before commit.  Without the ingest
    lock, sequence 2 could commit and become visible while sequence 1 was still
    open.  Holding the transaction-scoped lock through commit makes allocation
    order and visibility order agree.
    """

    try:
        async with session.begin():
            await _acquire_ingest_lock(session)
            # This check must happen after taking the lock. A concurrent retry
            # may have committed while this transaction was waiting.
            existing = await _existing_by_key(session, command.idempotency_key)
            if existing is not None:
                return _return_or_conflict(existing, command)
            session.add(command)
            await session.flush()
            await session.refresh(command)
    except IntegrityError:
        await session.rollback()
        async with session.begin():
            await _acquire_ingest_lock(session)
            existing = await _existing_by_key(session, command.idempotency_key)
            if existing is None:
                raise
            return _return_or_conflict(existing, command)

    return command


async def enqueue_submit(
    session: AsyncSession,
    *,
    idempotency_key: str,
    symbol: str,
    side: PersistedSide,
    price: int,
    quantity: int,
) -> MarketCommand:
    """Accept an order submission without waiting for matching to complete."""

    command = MarketCommand(
        idempotency_key=idempotency_key,
        command_type=CommandType.SUBMIT_ORDER,
        status=CommandStatus.QUEUED,
        symbol=symbol,
        payload={
            "order_id": str(uuid.uuid4()),
            "side": side.value,
            "price": price,
            "quantity": quantity,
        },
    )
    return await _persist_idempotently(session, command)


async def enqueue_cancel(
    session: AsyncSession,
    *,
    idempotency_key: str,
    symbol: str,
    order_id: str,
) -> MarketCommand:
    """Accept a cancellation for ordered background processing."""

    command = MarketCommand(
        idempotency_key=idempotency_key,
        command_type=CommandType.CANCEL_ORDER,
        status=CommandStatus.QUEUED,
        symbol=symbol,
        payload={"order_id": order_id},
    )
    return await _persist_idempotently(session, command)
